// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Opah_API.Infrastructure.Data;

namespace Opah_API.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Opah_API.Infrastructure.Model.TB_CIDADE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ESTADO")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TB_CIDADE");
                });

            modelBuilder.Entity("Opah_API.Infrastructure.Model.TB_CLIENTE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("COD_EMPRESA")
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("DATA_NASCIMENTO")
                        .HasColumnType("date");

                    b.Property<string>("EMAIL_")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TELEFONE")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("TB_CLIENTE");
                });

            modelBuilder.Entity("Opah_API.Infrastructure.Model.TB_ENDERECO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BAIRRO")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("COMPLEMENTO")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NUMERO")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RUA")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TB_CIDADE_ID")
                        .HasColumnType("int");

                    b.Property<int>("TB_CLIENTE_ID")
                        .HasColumnType("int");

                    b.Property<int>("TIPO_ENDERECO")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TB_CIDADE_ID");

                    b.HasIndex("TB_CLIENTE_ID");

                    b.ToTable("TB_ENDERECO");
                });

            modelBuilder.Entity("Opah_API.Infrastructure.Model.TB_ENDERECO", b =>
                {
                    b.HasOne("Opah_API.Infrastructure.Model.TB_CIDADE", "TB_CIDADE")
                        .WithMany("ENDERECOS")
                        .HasForeignKey("TB_CIDADE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Opah_API.Infrastructure.Model.TB_CLIENTE", "TB_CLIENTE")
                        .WithMany("ENDERECOS")
                        .HasForeignKey("TB_CLIENTE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TB_CIDADE");

                    b.Navigation("TB_CLIENTE");
                });

            modelBuilder.Entity("Opah_API.Infrastructure.Model.TB_CIDADE", b =>
                {
                    b.Navigation("ENDERECOS");
                });

            modelBuilder.Entity("Opah_API.Infrastructure.Model.TB_CLIENTE", b =>
                {
                    b.Navigation("ENDERECOS");
                });
#pragma warning restore 612, 618
        }
    }
}
